name: Deploy to Octopus Deploy

on:
  push:
    branches:
      - main
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository 
    - uses: actions/checkout@v2
    
    - name: Deploy to Octopus Deploy
      uses: OctopusDeploy/github-action@v1
      with:
        OctopusURL: https://test1.octopus.app/app#/Spaces-1/dashboard
        OctopusAPIKey: API-EY1UFU4LN22YUVRHMAYUTWLEW2YTOYQN
        Space: 'Default'
        Package: 'Test_Octopus_Deploy/Python/test_1.py'
        ReleaseVersion: '1.0.1'
