name: Deploy to Octopus Deploy

on:
  push:
    branches:
      - main
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository 
      uses: actions/checkout@v3
    
    - name: Push a package to Octopus Deploy
      uses: OctopusDeploy/push-package-action@v3
      env:
        OctopusURL: ${{https://test1.octopus.app/app#/Spaces-1/dashboard}}
        OctopusAPIKey: ${{API-EY1UFU4LN22YUVRHMAYUTWLEW2YTOYQN}}
        Space: 'Default'
      with:
        packages: |
            package1.tar.gz
            package2.zip
            packages/**/*.zip
