name: Deploy to Octopus Deploy

on:
  push:
    branches:
      - main
  
jobs:
  deploy:
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Push a package to Octopus Deploy
      uses: OctopusDeploy/OctopusDeploy-Api@v1
      env:
        OCTOPUS_URL: "https://test1.octopus.app/app#/Spaces-1/dashboard"
        OCTOPUS_API_KEY: "API-EY1UFU4LN22YUVRHMAYUTWLEW2YTOYQN"
        OCTOPUS_SPACE: 'Default'
      with:
        packages: 'Python/test.py'
